id: ID194E73E
legacy_id: P003181
ocr_import_info:
  bdrc_scan_id: W00EGS1017426
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T04:37:09'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T14:36:00.274803+00:00'
last_modified: 2022-08-30 22:42:53.089520
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W00EGS1017426
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW00EGS1017426
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། བཅོམ་ལྡན་རིག་པའི་རལ་གྲི།
  author: རིགས་པའི་རལ་གྲི།
statistics:
  ocr_word_mean_confidence_index: 0.8509638657644307
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I00EGS1017433:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1017433
      total_pages: 284
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I00EGS1017433.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9236531975278617
    legacy_id: v006
  I00EGS1017434:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1017434
      total_pages: 724
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I00EGS1017434.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9065113261764421
    legacy_id: v007
  I00EGS1017431:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1017431
      total_pages: 736
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I00EGS1017431.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.8746708612633309
    legacy_id: v004
  I00EGS1017429:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1017429
      total_pages: 626
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I00EGS1017429.txt
    statistics:
      ocr_word_median_confidence_index: 0.9599999785423279
      ocr_word_mean_confidence_index: 0.8062684360729512
    legacy_id: v002
  I00EGS1017437:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1017437
      total_pages: 192
      volume_number: 10
      volume_pages_bdrc_intro: 2
    order: 10
    base_file: I00EGS1017437.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8313855748391088
    legacy_id: v010
  I00EGS1017430:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1017430
      total_pages: 780
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I00EGS1017430.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.8829265731704125
    legacy_id: v003
  I00EGS1017432:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1017432
      total_pages: 698
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I00EGS1017432.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.7995493136534096
    legacy_id: v005
  I00EGS1017435:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1017435
      total_pages: 462
      volume_number: 8
      volume_pages_bdrc_intro: 2
    order: 8
    base_file: I00EGS1017435.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8220012658590387
    legacy_id: v008
  I00EGS1017436:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1017436
      total_pages: 632
      volume_number: 9
      volume_pages_bdrc_intro: 2
    order: 9
    base_file: I00EGS1017436.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8262330586022945
    legacy_id: v009
  I00EGS1017428:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1017428
      total_pages: 454
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I00EGS1017428.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8261508764808752
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
