id: ID194E73E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T04:38:27+00:00'
last_modified: '2022-06-07T18:08:07.681796+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00EGS1017426
  title: གསུང་འབུམ། བཅོམ་ལྡན་རིག་པའི་རལ་གྲི
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    19DD:
      image_group_id: I00EGS1017428
      title: ''
      total_pages: 454
      order: 1
      base_file: 19DD.txt
    3CA2:
      image_group_id: I00EGS1017429
      title: ''
      total_pages: 626
      order: 2
      base_file: 3CA2.txt
    '9887':
      image_group_id: I00EGS1017430
      title: ''
      total_pages: 780
      order: 3
      base_file: 9887.txt
    7D17:
      image_group_id: I00EGS1017431
      title: ''
      total_pages: 736
      order: 4
      base_file: 7D17.txt
    BAA8:
      image_group_id: I00EGS1017432
      title: ''
      total_pages: 698
      order: 5
      base_file: BAA8.txt
    CBE4:
      image_group_id: I00EGS1017433
      title: ''
      total_pages: 284
      order: 6
      base_file: CBE4.txt
    E0E2:
      image_group_id: I00EGS1017434
      title: ''
      total_pages: 724
      order: 7
      base_file: E0E2.txt
    E6BE:
      image_group_id: I00EGS1017435
      title: ''
      total_pages: 462
      order: 8
      base_file: E6BE.txt
    FD3D:
      image_group_id: I00EGS1017436
      title: ''
      total_pages: 632
      order: 9
      base_file: FD3D.txt
    '1414':
      image_group_id: I00EGS1017437
      title: ''
      total_pages: 192
      order: 10
      base_file: 1414.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
