id: P003181
initial_creation_type: ocr
source_metadata:
  id: bdr:W00EGS1017426
  title: གསུང་འབུམ། བཅོམ་ལྡན་རིག་པའི་རལ་གྲི
  author: ''
  volumes:
    dad49a5a129a41d9a39261441a2f5f6d:
      image_group_id: I00EGS1017428
      title: ''
      volume_number: 1
      total_pages: 454
      base_file: v001.txt
    f93cdd7f3d4342aca3a0112288214df8:
      image_group_id: I00EGS1017429
      title: ''
      volume_number: 2
      total_pages: 626
      base_file: v002.txt
    1f0db2fc0b2843a1890e26bc1acd3c60:
      image_group_id: I00EGS1017430
      title: ''
      volume_number: 3
      total_pages: 780
      base_file: v003.txt
    ce549b7cba9f43a993b016a332a18fb4:
      image_group_id: I00EGS1017431
      title: ''
      volume_number: 4
      total_pages: 736
      base_file: v004.txt
    dd525964a3124fe9863a534fb845ece3:
      image_group_id: I00EGS1017432
      title: ''
      volume_number: 5
      total_pages: 698
      base_file: v005.txt
    dbbb9644fe594aaea5e459a8786f3802:
      image_group_id: I00EGS1017433
      title: ''
      volume_number: 6
      total_pages: 284
      base_file: v006.txt
    8038669b9b1a4f5a96f90685e04c09e4:
      image_group_id: I00EGS1017434
      title: ''
      volume_number: 7
      total_pages: 724
      base_file: v007.txt
    d5ed41304d974886b23d62193eedf370:
      image_group_id: I00EGS1017435
      title: ''
      volume_number: 8
      total_pages: 462
      base_file: v008.txt
    25779f15651342d2a64fa9f137a2e332:
      image_group_id: I00EGS1017436
      title: ''
      volume_number: 9
      total_pages: 632
      base_file: v009.txt
    aef22477644a45f8b5837d7a8992f3ea:
      image_group_id: I00EGS1017437
      title: ''
      volume_number: 10
      total_pages: 192
      base_file: v010.txt
